# The latest version as installed by the Cygwin Setup program can
# always be found at /etc/defaults/etc/skel/.bash_profile

export HISTFILE="${HOME}/.homer/${HOMER_OS_TYPE}/bash_history"

PATH="${HOME}/.homer/${HOMER_OS_TYPE}/bin${PATH:+:${PATH}}"

. "${HOME}/.homer/${HOMER_OS_TYPE}/bashrc"
