if [ ! -z ${homer_debug+x} ]; then echo "Enter ${HOME}/.homer/${HOMER_OS_TYPE}/bash_profile"; fi

. "${HOME}/.homer/${HOMER_OS_TYPE}/bashrc"

if [ ! -z ${homer_debug+x} ]; then echo "Exit ${HOME}/.homer/${HOMER_OS_TYPE}/bash_profile"; fi
